config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    puts @article
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params 
    params.require(:article).permit(:title, :content);
  end

  def find_article 
    @article = Article.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_for(@article) do |f|  %>
 <%= f.label :title %>
 <%= f.text_field :title %><br><br>

 <%= f.label :content %>
 <%= f.text_field :content %><br><br>

 <%= f.submit %>
<% end %>

<p><%= link_to "Back to Articles", articles_path(@article) %></p>

    
    

    

app/views/articles/index.html.erb
<h1>Articles</h1>

<h2><%= link_to "New Article", new_article_path  %></h2> 

<% @articles.each do |article| %>
    <p><%= link_to article.title, article_path(article) %></p>
    <%= article.content %>
<% end %>

app/views/articles/new.html.erb
<%= form_for(@article) do |f|  %>
 <%= f.label :title %>
 <%= f.text_field :title %><br><br>

 <%= f.label :content %>
 <%= f.text_field :content %><br><br>

 <%= f.submit %>
<% end %>

<p><%= link_to "Back to Articles", articles_path(@article) %></p>

    
    

    

app/views/articles/show.html.erb
<h1>Article</h1> 

<%= @article.title %><br>
<%= @article.content %>

<br><br>
<p><%= link_to "Edit", edit_article_path(@article) %></p>

<p><%= link_to "Delete Article", article_path(@article), method: :delete %></p>

<p><%= link_to "Back to Articles", articles_path(@article) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>